version: "3"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - ./Settings:/config
      - ./TV:/tv
      - ./Movies:/movies
      - ./Series:/series
    #restart: unless-stopped
